export const TASKBOARD_VERSION = process.env.NEXT_PUBLIC_TASKBOARD_VERSION?.trim() || "V140"
export const TASKBOARD_BUILD_DATE = process.env.NEXT_PUBLIC_TASKBOARD_BUILD_DATE?.trim() || "--/-- --:--"

export const TASKBOARD_VERSION_LABEL = `${TASKBOARD_VERSION} - ${TASKBOARD_BUILD_DATE}`
